name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Клонируем репозиторий
        uses: actions/checkout@v4

      - name: 🚀 Подключаемся к серверу и разворачиваем приложение
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}   # Здесь указать IP вашего сервера
          username: ${{ secrets.SERVER_USER }}  # Здесь указать пользователя
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Закрытый SSH-ключ
          port: 22
          script: |
            cd githubActionsTest
            git pull origin master
            cd user-service
            mvn clean package -DskipTests
            cd ..
            cd document-service
            mvn clean package -DskipTests
            cd ..
            docker-compose down
            docker-compose build
            docker-compose up -d